// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutusDocumentDataSlicesSlice =
  | VisionDataSlice
  | AboutTeamSlice
  | ImageSlice
  | MainHeadingSlice
  | NavbarSlice
  | HeroSectionSlice
  | FooterSlice;

/**
 * Content for AboutUS documents
 */
interface AboutusDocumentData {
  /**
   * Slice Zone field in *AboutUS*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: aboutus.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutusDocumentDataSlicesSlice>;
}

/**
 * AboutUS document from Prismic
 *
 * - **API ID**: `aboutus`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutusDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutusDocumentData>,
    "aboutus",
    Lang
  >;

type BrochureDocumentDataSlicesSlice =
  | BrochureSlice
  | NavbarSlice
  | VideoSlice
  | MainHeadingSlice
  | HeroSectionSlice
  | FooterSlice;

/**
 * Content for Brochure documents
 */
interface BrochureDocumentData {
  /**
   * Slice Zone field in *Brochure*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: brochure.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BrochureDocumentDataSlicesSlice> /**
   * Meta Title field in *Brochure*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: brochure.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Brochure*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: brochure.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Brochure*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: brochure.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Brochure document from Prismic
 *
 * - **API ID**: `brochure`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BrochureDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BrochureDocumentData>,
    "brochure",
    Lang
  >;

type ContactusDocumentDataSlicesSlice =
  | ContactUsCitySlice
  | ContactUsDataSlice
  | NavbarSlice
  | MainHeadingSlice
  | HeroSectionSlice
  | FooterSlice;

/**
 * Content for ContactUs documents
 */
interface ContactusDocumentData {
  /**
   * Slice Zone field in *ContactUs*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contactus.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactusDocumentDataSlicesSlice> /**
   * Meta Title field in *ContactUs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contactus.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *ContactUs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contactus.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ContactUs*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contactus.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * ContactUs document from Prismic
 *
 * - **API ID**: `contactus`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactusDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactusDocumentData>,
    "contactus",
    Lang
  >;

type DoorsDocumentDataSlicesSlice =
  | ImageSlice
  | LeadingCompniesSlice
  | ProductsSlice
  | VeritySlice
  | WhyUsPointersWithVideoSlice
  | WindowCardsSlice
  | NavbarSlice
  | VideoSlice
  | MainHeadingSlice
  | HeroSectionSlice
  | FooterSlice;

/**
 * Content for Doors documents
 */
interface DoorsDocumentData {
  /**
   * Slice Zone field in *Doors*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: doors.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DoorsDocumentDataSlicesSlice> /**
   * Meta Title field in *Doors*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: doors.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Doors*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: doors.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Doors*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: doors.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Doors document from Prismic
 *
 * - **API ID**: `doors`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DoorsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<DoorsDocumentData>, "doors", Lang>;

type HomepageDocumentDataSlicesSlice =
  | VideoSlice
  | ScheduleCallSlice
  | ProductCardSlice
  | ProductionAndCallSlice
  | NavbarSlice
  | LeadingCompniesSlice
  | MainHeadingSlice
  | HeroSectionSlice
  | FooterSlice
  | ContactUsCitySlice
  | CardsSlice;

/**
 * Content for HomePage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type IndivisualproductDocumentDataSlicesSlice =
  | TableDataSlice
  | IndivisualProductImageDescSlice
  | ImageGallerySlice
  | AdvantagesDataForIndivisualProductSlice
  | ImageSlice
  | VideoSlice
  | MainHeadingSlice
  | NavbarSlice
  | HeroSectionSlice
  | FooterSlice;

/**
 * Content for IndivisualProduct documents
 */
interface IndivisualproductDocumentData {
  /**
   * Slice Zone field in *IndivisualProduct*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: indivisualproduct.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<IndivisualproductDocumentDataSlicesSlice> /**
   * Meta Title field in *IndivisualProduct*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: indivisualproduct.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *IndivisualProduct*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: indivisualproduct.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *IndivisualProduct*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: indivisualproduct.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * IndivisualProduct document from Prismic
 *
 * - **API ID**: `indivisualproduct`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndivisualproductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<IndivisualproductDocumentData>,
    "indivisualproduct",
    Lang
  >;

type PrivacypolicyDocumentDataSlicesSlice =
  | HeroSectionSlice
  | NavbarSlice
  | FooterSlice;

/**
 * Content for PrivacyPolicy documents
 */
interface PrivacypolicyDocumentData {
  /**
   * Slice Zone field in *PrivacyPolicy*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: privacypolicy.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PrivacypolicyDocumentDataSlicesSlice> /**
   * Meta Title field in *PrivacyPolicy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: privacypolicy.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *PrivacyPolicy*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: privacypolicy.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *PrivacyPolicy*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: privacypolicy.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * PrivacyPolicy document from Prismic
 *
 * - **API ID**: `privacypolicy`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrivacypolicyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PrivacypolicyDocumentData>,
    "privacypolicy",
    Lang
  >;

type WhyusDocumentDataSlicesSlice =
  | WhyUsPointersWithVideoSlice
  | WhyUsCardSlice
  | VideoSlice
  | NavbarSlice
  | MainHeadingSlice
  | HeroSectionSlice
  | FooterSlice;

/**
 * Content for WhyUs documents
 */
interface WhyusDocumentData {
  /**
   * Slice Zone field in *WhyUs*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: whyus.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WhyusDocumentDataSlicesSlice>;
}

/**
 * WhyUs document from Prismic
 *
 * - **API ID**: `whyus`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WhyusDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<WhyusDocumentData>, "whyus", Lang>;

type WindowsDocumentDataSlicesSlice =
  | LeadingCompniesSlice
  | VeritySlice
  | ImageSlice
  | ProductsSlice
  | WindowCardsSlice
  | WhyUsPointersWithVideoSlice
  | VideoSlice
  | NavbarSlice
  | MainHeadingSlice
  | HeroSectionSlice
  | FooterSlice;

/**
 * Content for Windows documents
 */
interface WindowsDocumentData {
  /**
   * Slice Zone field in *Windows*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: windows.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WindowsDocumentDataSlicesSlice> /**
   * Meta Title field in *Windows*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: windows.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Windows*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: windows.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Windows*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: windows.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Windows document from Prismic
 *
 * - **API ID**: `windows`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WindowsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<WindowsDocumentData>,
    "windows",
    Lang
  >;

export type AllDocumentTypes =
  | AboutusDocument
  | BrochureDocument
  | ContactusDocument
  | DoorsDocument
  | HomepageDocument
  | IndivisualproductDocument
  | PrivacypolicyDocument
  | WhyusDocument
  | WindowsDocument;

/**
 * Item in *AboutTeam → Default → Primary → TeamData*
 */
export interface AboutTeamSliceDefaultPrimaryTeamdataItem {
  /**
   * data field in *AboutTeam → Default → Primary → TeamData*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_team.default.primary.teamdata[].data
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  data: prismic.RichTextField;

  /**
   * image field in *AboutTeam → Default → Primary → TeamData*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_team.default.primary.teamdata[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *AboutTeam → Default → Primary*
 */
export interface AboutTeamSliceDefaultPrimary {
  /**
   * TeamData field in *AboutTeam → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about_team.default.primary.teamdata[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  teamdata: prismic.GroupField<
    Simplify<AboutTeamSliceDefaultPrimaryTeamdataItem>
  >;
}

/**
 * Default variation for AboutTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutTeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutTeam*
 */
type AboutTeamSliceVariation = AboutTeamSliceDefault;

/**
 * AboutTeam Shared Slice
 *
 * - **API ID**: `about_team`
 * - **Description**: AboutTeam
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTeamSlice = prismic.SharedSlice<
  "about_team",
  AboutTeamSliceVariation
>;

/**
 * Primary content in *AdvantagesDataForIndivisualProduct → Default → Primary*
 */
export interface AdvantagesDataForIndivisualProductSliceDefaultPrimary {
  /**
   * Title field in *AdvantagesDataForIndivisualProduct → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantages_data_for_indivisual_product.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *AdvantagesDataForIndivisualProduct → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: advantages_data_for_indivisual_product.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Items field in *AdvantagesDataForIndivisualProduct → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: advantages_data_for_indivisual_product.default.primary.items
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  items: prismic.RichTextField;
}

/**
 * Default variation for AdvantagesDataForIndivisualProduct Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvantagesDataForIndivisualProductSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<AdvantagesDataForIndivisualProductSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *AdvantagesDataForIndivisualProduct*
 */
type AdvantagesDataForIndivisualProductSliceVariation =
  AdvantagesDataForIndivisualProductSliceDefault;

/**
 * AdvantagesDataForIndivisualProduct Shared Slice
 *
 * - **API ID**: `advantages_data_for_indivisual_product`
 * - **Description**: AdvantagesDataForIndivisualProduct
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AdvantagesDataForIndivisualProductSlice = prismic.SharedSlice<
  "advantages_data_for_indivisual_product",
  AdvantagesDataForIndivisualProductSliceVariation
>;

/**
 * Item in *Brochure → Default → Primary → BrochureData*
 */
export interface BrochureSliceDefaultPrimaryBrochuredataItem {
  /**
   * Data field in *Brochure → Default → Primary → BrochureData*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: brochure.default.primary.brochuredata[].data
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  data: prismic.RichTextField;
}

/**
 * Primary content in *Brochure → Default → Primary*
 */
export interface BrochureSliceDefaultPrimary {
  /**
   * BrochureData field in *Brochure → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: brochure.default.primary.brochuredata[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  brochuredata: prismic.GroupField<
    Simplify<BrochureSliceDefaultPrimaryBrochuredataItem>
  >;
}

/**
 * Default variation for Brochure Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrochureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BrochureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Brochure*
 */
type BrochureSliceVariation = BrochureSliceDefault;

/**
 * Brochure Shared Slice
 *
 * - **API ID**: `brochure`
 * - **Description**: Brochure
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BrochureSlice = prismic.SharedSlice<
  "brochure",
  BrochureSliceVariation
>;

/**
 * Item in *Cards → Default → Primary → CardsData*
 */
export interface CardsSliceDefaultPrimaryCardsdataItem {
  /**
   * CardTitle field in *Cards → Default → Primary → CardsData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cardsdata[].CardTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  CardTitle: prismic.KeyTextField;

  /**
   * CardContent field in *Cards → Default → Primary → CardsData*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cardsdata[].cardcontent
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardcontent: prismic.RichTextField;
}

/**
 * Primary content in *Cards → Default → Primary*
 */
export interface CardsSliceDefaultPrimary {
  /**
   * CardsData field in *Cards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cardsdata[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cardsdata: prismic.GroupField<
    Simplify<CardsSliceDefaultPrimaryCardsdataItem>
  >;
}

/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cards*
 */
type CardsSliceVariation = CardsSliceDefault;

/**
 * Cards Shared Slice
 *
 * - **API ID**: `cards`
 * - **Description**: Cards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSlice = prismic.SharedSlice<"cards", CardsSliceVariation>;

/**
 * Item in *ContactUsCity → Default → Primary → Locations*
 */
export interface ContactUsCitySliceDefaultPrimaryLocationsItem {
  /**
   * City field in *ContactUsCity → Default → Primary → Locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_city.default.primary.locations[].city
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  city: prismic.KeyTextField;

  /**
   * State field in *ContactUsCity → Default → Primary → Locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_city.default.primary.locations[].state
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  state: prismic.KeyTextField;

  /**
   * Address field in *ContactUsCity → Default → Primary → Locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_city.default.primary.locations[].address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * locationLink field in *ContactUsCity → Default → Primary → Locations*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_city.default.primary.locations[].locationlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  locationlink: prismic.LinkField;
}

/**
 * Primary content in *ContactUsCity → Default → Primary*
 */
export interface ContactUsCitySliceDefaultPrimary {
  /**
   * Locations field in *ContactUsCity → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_city.default.primary.locations[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  locations: prismic.GroupField<
    Simplify<ContactUsCitySliceDefaultPrimaryLocationsItem>
  >;
}

/**
 * Default variation for ContactUsCity Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactUsCitySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactUsCitySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactUsCity*
 */
type ContactUsCitySliceVariation = ContactUsCitySliceDefault;

/**
 * ContactUsCity Shared Slice
 *
 * - **API ID**: `contact_us_city`
 * - **Description**: ContactUsCity
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactUsCitySlice = prismic.SharedSlice<
  "contact_us_city",
  ContactUsCitySliceVariation
>;

/**
 * Item in *ContactUsPage → Default → Primary → FounderData*
 */
export interface ContactUsDataSliceDefaultPrimaryFounderdataItem {
  /**
   * Name field in *ContactUsPage → Default → Primary → FounderData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_data.default.primary.founderdata[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Designation field in *ContactUsPage → Default → Primary → FounderData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_data.default.primary.founderdata[].designation
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  designation: prismic.KeyTextField;

  /**
   * Experience field in *ContactUsPage → Default → Primary → FounderData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_data.default.primary.founderdata[].experience
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  experience: prismic.KeyTextField;

  /**
   * SocialLinks field in *ContactUsPage → Default → Primary → FounderData*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_data.default.primary.founderdata[].sociallinks
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  sociallinks: prismic.RichTextField;
}

/**
 * Primary content in *ContactUsPage → Default → Primary*
 */
export interface ContactUsDataSliceDefaultPrimary {
  /**
   * FounderData field in *ContactUsPage → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_data.default.primary.founderdata[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  founderdata: prismic.GroupField<
    Simplify<ContactUsDataSliceDefaultPrimaryFounderdataItem>
  >;
}

/**
 * Default variation for ContactUsPage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactUsDataSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactUsDataSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactUsPage*
 */
type ContactUsDataSliceVariation = ContactUsDataSliceDefault;

/**
 * ContactUsPage Shared Slice
 *
 * - **API ID**: `contact_us_data`
 * - **Description**: ContactUsData
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactUsDataSlice = prismic.SharedSlice<
  "contact_us_data",
  ContactUsDataSliceVariation
>;

/**
 * Item in *Footer → Default → Primary → Links*
 */
export interface FooterSliceDefaultPrimaryLinksItem {
  /**
   * Links field in *Footer → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.links[].links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  links: prismic.LinkField;
}

/**
 * Item in *Footer → Default → Primary → Cities*
 */
export interface FooterSliceDefaultPrimaryCitiesItem {
  /**
   * Cities field in *Footer → Default → Primary → Cities*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.cities[].cities
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cities: prismic.LinkField;
}

/**
 * Item in *Footer → Default → Primary → SocialLinks*
 */
export interface FooterSliceDefaultPrimarySociallinksItem {
  /**
   * SocialLinks field in *Footer → Default → Primary → SocialLinks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.sociallinks[].sociallinks
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  sociallinks: prismic.LinkField;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Links field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryLinksItem>>;

  /**
   * Cities field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.cities[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cities: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryCitiesItem>>;

  /**
   * SocialLinks field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.sociallinks[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sociallinks: prismic.GroupField<
    Simplify<FooterSliceDefaultPrimarySociallinksItem>
  >;

  /**
   * Footerlogo field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.footerlogo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  footerlogo: prismic.ImageField<never>;

  /**
   * Email field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Phone field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone: prismic.KeyTextField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * HeroImage field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.heroimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroimage: prismic.ImageField<never>;

  /**
   * Heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *Image → Default → Primary*
 */
export interface ImageSliceDefaultPrimary {
  /**
   * Image field in *Image → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Image → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Image*
 */
type ImageSliceVariation = ImageSliceDefault;

/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: Image
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlice = prismic.SharedSlice<"image", ImageSliceVariation>;

/**
 * Item in *ImageGallery → Default → Primary → Images*
 */
export interface ImageGallerySliceDefaultPrimaryImagesItem {
  /**
   * Image field in *ImageGallery → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ImageGallery → Default → Primary → Images*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.default.primary.images[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *ImageGallery → Default → Primary*
 */
export interface ImageGallerySliceDefaultPrimary {
  /**
   * Images field in *ImageGallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_gallery.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<ImageGallerySliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for ImageGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageGallery*
 */
type ImageGallerySliceVariation = ImageGallerySliceDefault;

/**
 * ImageGallery Shared Slice
 *
 * - **API ID**: `image_gallery`
 * - **Description**: ImageGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageGallerySlice = prismic.SharedSlice<
  "image_gallery",
  ImageGallerySliceVariation
>;

/**
 * Item in *IndivisualProductImageDesc → Default → Primary → Data*
 */
export interface IndivisualProductImageDescSliceDefaultPrimaryDataItem {
  /**
   * Image field in *IndivisualProductImageDesc → Default → Primary → Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: indivisual_product_image_desc.default.primary.data[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *IndivisualProductImageDesc → Default → Primary → Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: indivisual_product_image_desc.default.primary.data[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *IndivisualProductImageDesc → Default → Primary → Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: indivisual_product_image_desc.default.primary.data[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *IndivisualProductImageDesc → Default → Primary*
 */
export interface IndivisualProductImageDescSliceDefaultPrimary {
  /**
   * Data field in *IndivisualProductImageDesc → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: indivisual_product_image_desc.default.primary.data[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  data: prismic.GroupField<
    Simplify<IndivisualProductImageDescSliceDefaultPrimaryDataItem>
  >;
}

/**
 * Default variation for IndivisualProductImageDesc Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IndivisualProductImageDescSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<IndivisualProductImageDescSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *IndivisualProductImageDesc*
 */
type IndivisualProductImageDescSliceVariation =
  IndivisualProductImageDescSliceDefault;

/**
 * IndivisualProductImageDesc Shared Slice
 *
 * - **API ID**: `indivisual_product_image_desc`
 * - **Description**: IndivisualProductImageDesc
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IndivisualProductImageDescSlice = prismic.SharedSlice<
  "indivisual_product_image_desc",
  IndivisualProductImageDescSliceVariation
>;

/**
 * Item in *LeadingCompnies → Default → Primary → compnies*
 */
export interface LeadingCompniesSliceDefaultPrimaryCompniesItem {
  /**
   * logo field in *LeadingCompnies → Default → Primary → compnies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: leading_compnies.default.primary.compnies[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Name field in *LeadingCompnies → Default → Primary → compnies*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: leading_compnies.default.primary.compnies[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;
}

/**
 * Primary content in *LeadingCompnies → Default → Primary*
 */
export interface LeadingCompniesSliceDefaultPrimary {
  /**
   * compnies field in *LeadingCompnies → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: leading_compnies.default.primary.compnies[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  compnies: prismic.GroupField<
    Simplify<LeadingCompniesSliceDefaultPrimaryCompniesItem>
  >;
}

/**
 * Default variation for LeadingCompnies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeadingCompniesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LeadingCompniesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LeadingCompnies*
 */
type LeadingCompniesSliceVariation = LeadingCompniesSliceDefault;

/**
 * LeadingCompnies Shared Slice
 *
 * - **API ID**: `leading_compnies`
 * - **Description**: LeadingCompnies
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeadingCompniesSlice = prismic.SharedSlice<
  "leading_compnies",
  LeadingCompniesSliceVariation
>;

/**
 * Primary content in *MainHeading → Default → Primary*
 */
export interface MainHeadingSliceDefaultPrimary {
  /**
   * Heading field in *MainHeading → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: uPVC Product
   * - **API ID Path**: main_heading.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * subheading field in *MainHeading → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: uPVC Product details
   * - **API ID Path**: main_heading.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * paragraph field in *MainHeading → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_heading.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for MainHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MainHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MainHeading*
 */
type MainHeadingSliceVariation = MainHeadingSliceDefault;

/**
 * MainHeading Shared Slice
 *
 * - **API ID**: `main_heading`
 * - **Description**: MainHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainHeadingSlice = prismic.SharedSlice<
  "main_heading",
  MainHeadingSliceVariation
>;

/**
 * Item in *Navbar → Default → Primary → Routes*
 */
export interface NavbarSliceDefaultPrimaryRoutesItem {
  /**
   * Route field in *Navbar → Default → Primary → Routes*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.routes[].route
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  route: prismic.LinkField;
}

/**
 * Primary content in *Navbar → Default → Primary*
 */
export interface NavbarSliceDefaultPrimary {
  /**
   * logoSrc field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.logosrc
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logosrc: prismic.ImageField<never>;

  /**
   * Routes field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.routes[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  routes: prismic.GroupField<Simplify<NavbarSliceDefaultPrimaryRoutesItem>>;

  /**
   * videoroute field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.videoroute
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  videoroute: prismic.KeyTextField;

  /**
   * email field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * phonenumber field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.phonenumber
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phonenumber: prismic.KeyTextField;
}

/**
 * Default variation for Navbar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavbarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Navbar*
 */
type NavbarSliceVariation = NavbarSliceDefault;

/**
 * Navbar Shared Slice
 *
 * - **API ID**: `navbar`
 * - **Description**: Navbar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarSlice = prismic.SharedSlice<"navbar", NavbarSliceVariation>;

/**
 * Item in *ProductCard → Default → Primary → ProductCard*
 */
export interface ProductCardSliceDefaultPrimaryProductcardItem {
  /**
   * productImage field in *ProductCard → Default → Primary → ProductCard*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.default.primary.productcard[].productimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  productimage: prismic.ImageField<never>;

  /**
   * ProductLink field in *ProductCard → Default → Primary → ProductCard*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.default.primary.productcard[].productlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  productlink: prismic.LinkField;
}

/**
 * Primary content in *ProductCard → Default → Primary*
 */
export interface ProductCardSliceDefaultPrimary {
  /**
   * ProductCard field in *ProductCard → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.default.primary.productcard[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  productcard: prismic.GroupField<
    Simplify<ProductCardSliceDefaultPrimaryProductcardItem>
  >;
}

/**
 * Default variation for ProductCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductCard*
 */
type ProductCardSliceVariation = ProductCardSliceDefault;

/**
 * ProductCard Shared Slice
 *
 * - **API ID**: `product_card`
 * - **Description**: ProductCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductCardSlice = prismic.SharedSlice<
  "product_card",
  ProductCardSliceVariation
>;

/**
 * Primary content in *ProductionAndCall → Default → Primary*
 */
export interface ProductionAndCallSliceDefaultPrimary {
  /**
   * logoSrc field in *ProductionAndCall → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: production_and_call.default.primary.logosrc
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logosrc: prismic.ImageField<never>;

  /**
   * ProductionProcessTitle field in *ProductionAndCall → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: production_and_call.default.primary.productionprocesstitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  productionprocesstitle: prismic.KeyTextField;

  /**
   * productionCapacityNumber field in *ProductionAndCall → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: production_and_call.default.primary.productioncapacitynumber
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  productioncapacitynumber: prismic.KeyTextField;

  /**
   * productionCapacityUnit field in *ProductionAndCall → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: production_and_call.default.primary.productioncapacityunit
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  productioncapacityunit: prismic.KeyTextField;

  /**
   * yearsOfExperienceNumber field in *ProductionAndCall → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: production_and_call.default.primary.yearsofexperiencenumber
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  yearsofexperiencenumber: prismic.KeyTextField;

  /**
   * yearsOfExperienceText field in *ProductionAndCall → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: production_and_call.default.primary.yearsofexperiencetext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  yearsofexperiencetext: prismic.KeyTextField;
}

/**
 * Default variation for ProductionAndCall Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductionAndCallSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductionAndCallSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductionAndCall*
 */
type ProductionAndCallSliceVariation = ProductionAndCallSliceDefault;

/**
 * ProductionAndCall Shared Slice
 *
 * - **API ID**: `production_and_call`
 * - **Description**: ProductionAndCall
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductionAndCallSlice = prismic.SharedSlice<
  "production_and_call",
  ProductionAndCallSliceVariation
>;

/**
 * Item in *Products → Default → Primary → ProductsData*
 */
export interface ProductsSliceDefaultPrimaryProductsdataItem {
  /**
   * Image field in *Products → Default → Primary → ProductsData*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.productsdata[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Products → Default → Primary → ProductsData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.productsdata[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Products → Default → Primary → ProductsData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.productsdata[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Advantages field in *Products → Default → Primary → ProductsData*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.productsdata[].advantages
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  advantages: prismic.RichTextField;

  /**
   * Link field in *Products → Default → Primary → ProductsData*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.productsdata[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Products → Default → Primary*
 */
export interface ProductsSliceDefaultPrimary {
  /**
   * ProductsData field in *Products → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.productsdata[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  productsdata: prismic.GroupField<
    Simplify<ProductsSliceDefaultPrimaryProductsdataItem>
  >;
}

/**
 * Default variation for Products Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Products*
 */
type ProductsSliceVariation = ProductsSliceDefault;

/**
 * Products Shared Slice
 *
 * - **API ID**: `products`
 * - **Description**: Products
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSlice = prismic.SharedSlice<
  "products",
  ProductsSliceVariation
>;

/**
 * Primary content in *ScheduleCall → Default → Primary*
 */
export interface ScheduleCallSliceDefaultPrimary {
  /**
   * logo field in *ScheduleCall → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule_call.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Title field in *ScheduleCall → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule_call.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * button field in *ScheduleCall → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule_call.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField;
}

/**
 * Default variation for ScheduleCall Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScheduleCallSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScheduleCallSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ScheduleCall*
 */
type ScheduleCallSliceVariation = ScheduleCallSliceDefault;

/**
 * ScheduleCall Shared Slice
 *
 * - **API ID**: `schedule_call`
 * - **Description**: ScheduleCall
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScheduleCallSlice = prismic.SharedSlice<
  "schedule_call",
  ScheduleCallSliceVariation
>;

/**
 * Item in *TableData → Default → Primary → TableData*
 */
export interface TableDataSliceDefaultPrimaryTabledataItem {
  /**
   * Heading field in *TableData → Default → Primary → TableData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: table_data.default.primary.tabledata[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * minWidth field in *TableData → Default → Primary → TableData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: table_data.default.primary.tabledata[].minwidth
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  minwidth: prismic.KeyTextField;

  /**
   * minHeight field in *TableData → Default → Primary → TableData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: table_data.default.primary.tabledata[].minheight
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  minheight: prismic.KeyTextField;

  /**
   * maxWidth field in *TableData → Default → Primary → TableData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: table_data.default.primary.tabledata[].maxwidth
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  maxwidth: prismic.KeyTextField;

  /**
   * maxHeight field in *TableData → Default → Primary → TableData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: table_data.default.primary.tabledata[].maxheight
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  maxheight: prismic.KeyTextField;
}

/**
 * Primary content in *TableData → Default → Primary*
 */
export interface TableDataSliceDefaultPrimary {
  /**
   * TableData field in *TableData → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: table_data.default.primary.tabledata[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tabledata: prismic.GroupField<
    Simplify<TableDataSliceDefaultPrimaryTabledataItem>
  >;
}

/**
 * Default variation for TableData Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableDataSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TableDataSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TableData*
 */
type TableDataSliceVariation = TableDataSliceDefault;

/**
 * TableData Shared Slice
 *
 * - **API ID**: `table_data`
 * - **Description**: TableData
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TableDataSlice = prismic.SharedSlice<
  "table_data",
  TableDataSliceVariation
>;

/**
 * Item in *Veriety → Default → Primary → VerityData*
 */
export interface VeritySliceDefaultPrimaryVeritydataItem {
  /**
   * Title field in *Veriety → Default → Primary → VerityData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: verity.default.primary.veritydata[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Veriety → Default → Primary → VerityData*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: verity.default.primary.veritydata[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Veriety → Default → Primary*
 */
export interface VeritySliceDefaultPrimary {
  /**
   * VerityData field in *Veriety → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: verity.default.primary.veritydata[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  veritydata: prismic.GroupField<
    Simplify<VeritySliceDefaultPrimaryVeritydataItem>
  >;
}

/**
 * Default variation for Veriety Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VeritySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VeritySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Veriety*
 */
type VeritySliceVariation = VeritySliceDefault;

/**
 * Veriety Shared Slice
 *
 * - **API ID**: `verity`
 * - **Description**: Verity
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VeritySlice = prismic.SharedSlice<"verity", VeritySliceVariation>;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * videolink field in *Video → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: videosrc
   * - **API ID Path**: video.default.primary.videolink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  videolink: prismic.KeyTextField;

  /**
   * videodata field in *Video → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.videodata
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  videodata: prismic.LinkToMediaField;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

/**
 * Item in *VisionData → Default → Primary → VisionData*
 */
export interface VisionDataSliceDefaultPrimaryVisiondataItem {
  /**
   * image field in *VisionData → Default → Primary → VisionData*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_data.default.primary.visiondata[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *VisionData → Default → Primary → VisionData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_data.default.primary.visiondata[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *VisionData → Default → Primary → VisionData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_data.default.primary.visiondata[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *VisionData → Default → Primary*
 */
export interface VisionDataSliceDefaultPrimary {
  /**
   * VisionData field in *VisionData → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_data.default.primary.visiondata[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  visiondata: prismic.GroupField<
    Simplify<VisionDataSliceDefaultPrimaryVisiondataItem>
  >;
}

/**
 * Default variation for VisionData Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisionDataSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VisionDataSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VisionData*
 */
type VisionDataSliceVariation = VisionDataSliceDefault;

/**
 * VisionData Shared Slice
 *
 * - **API ID**: `vision_data`
 * - **Description**: VisionData
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisionDataSlice = prismic.SharedSlice<
  "vision_data",
  VisionDataSliceVariation
>;

/**
 * Item in *WhyUsCard → Default → Primary → Card*
 */
export interface WhyUsCardSliceDefaultPrimaryCardItem {
  /**
   * CardLogo field in *WhyUsCard → Default → Primary → Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: why_us_card.default.primary.card[].cardlogo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardlogo: prismic.ImageField<never>;

  /**
   * CardTitle field in *WhyUsCard → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_us_card.default.primary.card[].cardtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardtitle: prismic.KeyTextField;

  /**
   * CardContent field in *WhyUsCard → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_us_card.default.primary.card[].cardcontent
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardcontent: prismic.KeyTextField;
}

/**
 * Primary content in *WhyUsCard → Default → Primary*
 */
export interface WhyUsCardSliceDefaultPrimary {
  /**
   * Card field in *WhyUsCard → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: why_us_card.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<WhyUsCardSliceDefaultPrimaryCardItem>>;
}

/**
 * Default variation for WhyUsCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyUsCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhyUsCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhyUsCard*
 */
type WhyUsCardSliceVariation = WhyUsCardSliceDefault;

/**
 * WhyUsCard Shared Slice
 *
 * - **API ID**: `why_us_card`
 * - **Description**: WhyUsCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyUsCardSlice = prismic.SharedSlice<
  "why_us_card",
  WhyUsCardSliceVariation
>;

/**
 * Item in *ProductPointersWithVideo → Default → Primary → Data*
 */
export interface WhyUsPointersWithVideoSliceDefaultPrimaryDataItem {
  /**
   * Heading field in *ProductPointersWithVideo → Default → Primary → Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_us_pointers_with_video.default.primary.data[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Text field in *ProductPointersWithVideo → Default → Primary → Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_us_pointers_with_video.default.primary.data[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * Video field in *ProductPointersWithVideo → Default → Primary → Data*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: why_us_pointers_with_video.default.primary.data[].video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkField;
}

/**
 * Primary content in *ProductPointersWithVideo → Default → Primary*
 */
export interface WhyUsPointersWithVideoSliceDefaultPrimary {
  /**
   * Data field in *ProductPointersWithVideo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: why_us_pointers_with_video.default.primary.data[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  data: prismic.GroupField<
    Simplify<WhyUsPointersWithVideoSliceDefaultPrimaryDataItem>
  >;
}

/**
 * Default variation for ProductPointersWithVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyUsPointersWithVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhyUsPointersWithVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductPointersWithVideo*
 */
type WhyUsPointersWithVideoSliceVariation = WhyUsPointersWithVideoSliceDefault;

/**
 * ProductPointersWithVideo Shared Slice
 *
 * - **API ID**: `why_us_pointers_with_video`
 * - **Description**: WhyUsPointersWithVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhyUsPointersWithVideoSlice = prismic.SharedSlice<
  "why_us_pointers_with_video",
  WhyUsPointersWithVideoSliceVariation
>;

/**
 * Item in *WindowCards → Default → Primary → Cards*
 */
export interface WindowCardsSliceDefaultPrimaryCardsItem {
  /**
   * image field in *WindowCards → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: window_cards.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *WindowCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: window_cards.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *WindowCards → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: window_cards.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *WindowCards → Default → Primary*
 */
export interface WindowCardsSliceDefaultPrimary {
  /**
   * Cards field in *WindowCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: window_cards.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cards: prismic.GroupField<Simplify<WindowCardsSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for WindowCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WindowCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WindowCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WindowCards*
 */
type WindowCardsSliceVariation = WindowCardsSliceDefault;

/**
 * WindowCards Shared Slice
 *
 * - **API ID**: `window_cards`
 * - **Description**: WindowCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WindowCardsSlice = prismic.SharedSlice<
  "window_cards",
  WindowCardsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutusDocument,
      AboutusDocumentData,
      AboutusDocumentDataSlicesSlice,
      BrochureDocument,
      BrochureDocumentData,
      BrochureDocumentDataSlicesSlice,
      ContactusDocument,
      ContactusDocumentData,
      ContactusDocumentDataSlicesSlice,
      DoorsDocument,
      DoorsDocumentData,
      DoorsDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      IndivisualproductDocument,
      IndivisualproductDocumentData,
      IndivisualproductDocumentDataSlicesSlice,
      PrivacypolicyDocument,
      PrivacypolicyDocumentData,
      PrivacypolicyDocumentDataSlicesSlice,
      WhyusDocument,
      WhyusDocumentData,
      WhyusDocumentDataSlicesSlice,
      WindowsDocument,
      WindowsDocumentData,
      WindowsDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutTeamSlice,
      AboutTeamSliceDefaultPrimaryTeamdataItem,
      AboutTeamSliceDefaultPrimary,
      AboutTeamSliceVariation,
      AboutTeamSliceDefault,
      AdvantagesDataForIndivisualProductSlice,
      AdvantagesDataForIndivisualProductSliceDefaultPrimary,
      AdvantagesDataForIndivisualProductSliceVariation,
      AdvantagesDataForIndivisualProductSliceDefault,
      BrochureSlice,
      BrochureSliceDefaultPrimaryBrochuredataItem,
      BrochureSliceDefaultPrimary,
      BrochureSliceVariation,
      BrochureSliceDefault,
      CardsSlice,
      CardsSliceDefaultPrimaryCardsdataItem,
      CardsSliceDefaultPrimary,
      CardsSliceVariation,
      CardsSliceDefault,
      ContactUsCitySlice,
      ContactUsCitySliceDefaultPrimaryLocationsItem,
      ContactUsCitySliceDefaultPrimary,
      ContactUsCitySliceVariation,
      ContactUsCitySliceDefault,
      ContactUsDataSlice,
      ContactUsDataSliceDefaultPrimaryFounderdataItem,
      ContactUsDataSliceDefaultPrimary,
      ContactUsDataSliceVariation,
      ContactUsDataSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimaryLinksItem,
      FooterSliceDefaultPrimaryCitiesItem,
      FooterSliceDefaultPrimarySociallinksItem,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      ImageSlice,
      ImageSliceDefaultPrimary,
      ImageSliceVariation,
      ImageSliceDefault,
      ImageGallerySlice,
      ImageGallerySliceDefaultPrimaryImagesItem,
      ImageGallerySliceDefaultPrimary,
      ImageGallerySliceVariation,
      ImageGallerySliceDefault,
      IndivisualProductImageDescSlice,
      IndivisualProductImageDescSliceDefaultPrimaryDataItem,
      IndivisualProductImageDescSliceDefaultPrimary,
      IndivisualProductImageDescSliceVariation,
      IndivisualProductImageDescSliceDefault,
      LeadingCompniesSlice,
      LeadingCompniesSliceDefaultPrimaryCompniesItem,
      LeadingCompniesSliceDefaultPrimary,
      LeadingCompniesSliceVariation,
      LeadingCompniesSliceDefault,
      MainHeadingSlice,
      MainHeadingSliceDefaultPrimary,
      MainHeadingSliceVariation,
      MainHeadingSliceDefault,
      NavbarSlice,
      NavbarSliceDefaultPrimaryRoutesItem,
      NavbarSliceDefaultPrimary,
      NavbarSliceVariation,
      NavbarSliceDefault,
      ProductCardSlice,
      ProductCardSliceDefaultPrimaryProductcardItem,
      ProductCardSliceDefaultPrimary,
      ProductCardSliceVariation,
      ProductCardSliceDefault,
      ProductionAndCallSlice,
      ProductionAndCallSliceDefaultPrimary,
      ProductionAndCallSliceVariation,
      ProductionAndCallSliceDefault,
      ProductsSlice,
      ProductsSliceDefaultPrimaryProductsdataItem,
      ProductsSliceDefaultPrimary,
      ProductsSliceVariation,
      ProductsSliceDefault,
      ScheduleCallSlice,
      ScheduleCallSliceDefaultPrimary,
      ScheduleCallSliceVariation,
      ScheduleCallSliceDefault,
      TableDataSlice,
      TableDataSliceDefaultPrimaryTabledataItem,
      TableDataSliceDefaultPrimary,
      TableDataSliceVariation,
      TableDataSliceDefault,
      VeritySlice,
      VeritySliceDefaultPrimaryVeritydataItem,
      VeritySliceDefaultPrimary,
      VeritySliceVariation,
      VeritySliceDefault,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
      VisionDataSlice,
      VisionDataSliceDefaultPrimaryVisiondataItem,
      VisionDataSliceDefaultPrimary,
      VisionDataSliceVariation,
      VisionDataSliceDefault,
      WhyUsCardSlice,
      WhyUsCardSliceDefaultPrimaryCardItem,
      WhyUsCardSliceDefaultPrimary,
      WhyUsCardSliceVariation,
      WhyUsCardSliceDefault,
      WhyUsPointersWithVideoSlice,
      WhyUsPointersWithVideoSliceDefaultPrimaryDataItem,
      WhyUsPointersWithVideoSliceDefaultPrimary,
      WhyUsPointersWithVideoSliceVariation,
      WhyUsPointersWithVideoSliceDefault,
      WindowCardsSlice,
      WindowCardsSliceDefaultPrimaryCardsItem,
      WindowCardsSliceDefaultPrimary,
      WindowCardsSliceVariation,
      WindowCardsSliceDefault,
    };
  }
}
