// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | FooterSlice
  | ScheduleCallSlice
  | LeadingCompniesSlice
  | ContactUsCitySlice
  | ProductionAndCallSlice
  | ProductCardSlice
  | CardsSlice
  | VideoSlice
  | MainHeadingSlice
  | HeroSectionSlice
  | NavbarSlice;

type PageDocumentDataSlices1Slice = never;

/**
 * Content for HomePage documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *HomePage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *HomePage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *HomePage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices1[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices1: prismic.SliceZone<PageDocumentDataSlices1Slice>;
}

/**
 * HomePage document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Item in *Cards → Default → Primary → CardsData*
 */
export interface CardsSliceDefaultPrimaryCardsdataItem {
  /**
   * CardTitle field in *Cards → Default → Primary → CardsData*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cardsdata[].CardTitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  CardTitle: prismic.KeyTextField;

  /**
   * CardContent field in *Cards → Default → Primary → CardsData*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cardsdata[].cardcontent
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardcontent: prismic.RichTextField;
}

/**
 * Primary content in *Cards → Default → Primary*
 */
export interface CardsSliceDefaultPrimary {
  /**
   * CardsData field in *Cards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cards.default.primary.cardsdata[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cardsdata: prismic.GroupField<
    Simplify<CardsSliceDefaultPrimaryCardsdataItem>
  >;
}

/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cards*
 */
type CardsSliceVariation = CardsSliceDefault;

/**
 * Cards Shared Slice
 *
 * - **API ID**: `cards`
 * - **Description**: Cards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSlice = prismic.SharedSlice<"cards", CardsSliceVariation>;

/**
 * Item in *ContactUsCity → Default → Primary → Locations*
 */
export interface ContactUsCitySliceDefaultPrimaryLocationsItem {
  /**
   * City field in *ContactUsCity → Default → Primary → Locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_city.default.primary.locations[].city
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  city: prismic.KeyTextField;

  /**
   * State field in *ContactUsCity → Default → Primary → Locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_city.default.primary.locations[].state
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  state: prismic.KeyTextField;

  /**
   * Address field in *ContactUsCity → Default → Primary → Locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_city.default.primary.locations[].address
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * locationLink field in *ContactUsCity → Default → Primary → Locations*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_city.default.primary.locations[].locationlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  locationlink: prismic.LinkField;
}

/**
 * Primary content in *ContactUsCity → Default → Primary*
 */
export interface ContactUsCitySliceDefaultPrimary {
  /**
   * Locations field in *ContactUsCity → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_us_city.default.primary.locations[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  locations: prismic.GroupField<
    Simplify<ContactUsCitySliceDefaultPrimaryLocationsItem>
  >;
}

/**
 * Default variation for ContactUsCity Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactUsCitySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactUsCitySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactUsCity*
 */
type ContactUsCitySliceVariation = ContactUsCitySliceDefault;

/**
 * ContactUsCity Shared Slice
 *
 * - **API ID**: `contact_us_city`
 * - **Description**: ContactUsCity
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactUsCitySlice = prismic.SharedSlice<
  "contact_us_city",
  ContactUsCitySliceVariation
>;

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * HeroImage field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.heroimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heroimage: prismic.ImageField<never>;

  /**
   * Heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Default variation for LeadingCompnies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeadingCompniesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *LeadingCompnies*
 */
type LeadingCompniesSliceVariation = LeadingCompniesSliceDefault;

/**
 * LeadingCompnies Shared Slice
 *
 * - **API ID**: `leading_compnies`
 * - **Description**: LeadingCompnies
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeadingCompniesSlice = prismic.SharedSlice<
  "leading_compnies",
  LeadingCompniesSliceVariation
>;

/**
 * Primary content in *MainHeading → Default → Primary*
 */
export interface MainHeadingSliceDefaultPrimary {
  /**
   * Heading field in *MainHeading → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: uPVC Product
   * - **API ID Path**: main_heading.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * subheading field in *MainHeading → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: uPVC Product details
   * - **API ID Path**: main_heading.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subheading: prismic.KeyTextField;

  /**
   * paragraph field in *MainHeading → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: main_heading.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for MainHeading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainHeadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MainHeadingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MainHeading*
 */
type MainHeadingSliceVariation = MainHeadingSliceDefault;

/**
 * MainHeading Shared Slice
 *
 * - **API ID**: `main_heading`
 * - **Description**: MainHeading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MainHeadingSlice = prismic.SharedSlice<
  "main_heading",
  MainHeadingSliceVariation
>;

/**
 * Item in *Navbar → Default → Primary → Routes*
 */
export interface NavbarSliceDefaultPrimaryRoutesItem {
  /**
   * Route field in *Navbar → Default → Primary → Routes*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.routes[].route
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  route: prismic.LinkField;
}

/**
 * Primary content in *Navbar → Default → Primary*
 */
export interface NavbarSliceDefaultPrimary {
  /**
   * logoSrc field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.logosrc
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logosrc: prismic.ImageField<never>;

  /**
   * Routes field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.routes[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  routes: prismic.GroupField<Simplify<NavbarSliceDefaultPrimaryRoutesItem>>;

  /**
   * videoroute field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.videoroute
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  videoroute: prismic.KeyTextField;

  /**
   * email field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * phonenumber field in *Navbar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.default.primary.phonenumber
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phonenumber: prismic.KeyTextField;
}

/**
 * Default variation for Navbar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavbarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Navbar*
 */
type NavbarSliceVariation = NavbarSliceDefault;

/**
 * Navbar Shared Slice
 *
 * - **API ID**: `navbar`
 * - **Description**: Navbar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NavbarSlice = prismic.SharedSlice<"navbar", NavbarSliceVariation>;

/**
 * Item in *ProductCard → Default → Primary → ProductCard*
 */
export interface ProductCardSliceDefaultPrimaryProductcardItem {
  /**
   * productImage field in *ProductCard → Default → Primary → ProductCard*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.default.primary.productcard[].productimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  productimage: prismic.ImageField<never>;

  /**
   * ProductLink field in *ProductCard → Default → Primary → ProductCard*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.default.primary.productcard[].productlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  productlink: prismic.LinkField;
}

/**
 * Primary content in *ProductCard → Default → Primary*
 */
export interface ProductCardSliceDefaultPrimary {
  /**
   * ProductCard field in *ProductCard → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.default.primary.productcard[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  productcard: prismic.GroupField<
    Simplify<ProductCardSliceDefaultPrimaryProductcardItem>
  >;
}

/**
 * Default variation for ProductCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductCard*
 */
type ProductCardSliceVariation = ProductCardSliceDefault;

/**
 * ProductCard Shared Slice
 *
 * - **API ID**: `product_card`
 * - **Description**: ProductCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductCardSlice = prismic.SharedSlice<
  "product_card",
  ProductCardSliceVariation
>;

/**
 * Primary content in *ProductionAndCall → Default → Primary*
 */
export interface ProductionAndCallSliceDefaultPrimary {
  /**
   * logoSrc field in *ProductionAndCall → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: production_and_call.default.primary.logosrc
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logosrc: prismic.ImageField<never>;

  /**
   * ProductionProcessTitle field in *ProductionAndCall → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: production_and_call.default.primary.productionprocesstitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  productionprocesstitle: prismic.KeyTextField;

  /**
   * productionCapacityNumber field in *ProductionAndCall → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: production_and_call.default.primary.productioncapacitynumber
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  productioncapacitynumber: prismic.KeyTextField;

  /**
   * productionCapacityUnit field in *ProductionAndCall → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: production_and_call.default.primary.productioncapacityunit
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  productioncapacityunit: prismic.KeyTextField;

  /**
   * yearsOfExperienceNumber field in *ProductionAndCall → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: production_and_call.default.primary.yearsofexperiencenumber
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  yearsofexperiencenumber: prismic.KeyTextField;

  /**
   * yearsOfExperienceText field in *ProductionAndCall → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: production_and_call.default.primary.yearsofexperiencetext
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  yearsofexperiencetext: prismic.KeyTextField;
}

/**
 * Default variation for ProductionAndCall Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductionAndCallSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductionAndCallSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductionAndCall*
 */
type ProductionAndCallSliceVariation = ProductionAndCallSliceDefault;

/**
 * ProductionAndCall Shared Slice
 *
 * - **API ID**: `production_and_call`
 * - **Description**: ProductionAndCall
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductionAndCallSlice = prismic.SharedSlice<
  "production_and_call",
  ProductionAndCallSliceVariation
>;

/**
 * Primary content in *ScheduleCall → Default → Primary*
 */
export interface ScheduleCallSliceDefaultPrimary {
  /**
   * logo field in *ScheduleCall → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule_call.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Title field in *ScheduleCall → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule_call.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * button field in *ScheduleCall → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: schedule_call.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField;
}

/**
 * Default variation for ScheduleCall Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScheduleCallSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ScheduleCallSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ScheduleCall*
 */
type ScheduleCallSliceVariation = ScheduleCallSliceDefault;

/**
 * ScheduleCall Shared Slice
 *
 * - **API ID**: `schedule_call`
 * - **Description**: ScheduleCall
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ScheduleCallSlice = prismic.SharedSlice<
  "schedule_call",
  ScheduleCallSliceVariation
>;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * videolink field in *Video → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: videosrc
   * - **API ID Path**: video.default.primary.videolink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  videolink: prismic.KeyTextField;

  /**
   * videodata field in *Video → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.videodata
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  videodata: prismic.LinkToMediaField;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocumentDataSlices1Slice,
      AllDocumentTypes,
      CardsSlice,
      CardsSliceDefaultPrimaryCardsdataItem,
      CardsSliceDefaultPrimary,
      CardsSliceVariation,
      CardsSliceDefault,
      ContactUsCitySlice,
      ContactUsCitySliceDefaultPrimaryLocationsItem,
      ContactUsCitySliceDefaultPrimary,
      ContactUsCitySliceVariation,
      ContactUsCitySliceDefault,
      FooterSlice,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      LeadingCompniesSlice,
      LeadingCompniesSliceVariation,
      LeadingCompniesSliceDefault,
      MainHeadingSlice,
      MainHeadingSliceDefaultPrimary,
      MainHeadingSliceVariation,
      MainHeadingSliceDefault,
      NavbarSlice,
      NavbarSliceDefaultPrimaryRoutesItem,
      NavbarSliceDefaultPrimary,
      NavbarSliceVariation,
      NavbarSliceDefault,
      ProductCardSlice,
      ProductCardSliceDefaultPrimaryProductcardItem,
      ProductCardSliceDefaultPrimary,
      ProductCardSliceVariation,
      ProductCardSliceDefault,
      ProductionAndCallSlice,
      ProductionAndCallSliceDefaultPrimary,
      ProductionAndCallSliceVariation,
      ProductionAndCallSliceDefault,
      ScheduleCallSlice,
      ScheduleCallSliceDefaultPrimary,
      ScheduleCallSliceVariation,
      ScheduleCallSliceDefault,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
    };
  }
}
